<script setup>
import { getAuth, onAuthStateChanged } from 'firebase/auth'
import { ref, onMounted, computed } from 'vue'
import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from '../firebase' // Ensure this path matches where you put firebase.js

const designs = ref([])
const loading = ref(true)
const currentUser = ref(null)
const galleryFilter = ref({ breed: '', sport: '', customizable: '', includeAiAssisted: true })

const uniqueBreeds = computed(() => [...new Set(designs.value.flatMap(d => d.breeds || []))].sort())
const uniqueSports = computed(() => [...new Set(designs.value.flatMap(d => d.sports || []))].sort())

const filteredGalleryDesigns = computed(() => {
  return designs.value.filter(d => {
    const matchBreed = galleryFilter.value.breed === '' || (d.breeds && d.breeds.includes(galleryFilter.value.breed))
    const matchSport = galleryFilter.value.sport === '' || (d.sports && d.sports.includes(galleryFilter.value.sport))
    const matchCustom = galleryFilter.value.customizable === '' || 
                        (galleryFilter.value.customizable === 'yes' && d.isCustomizable) || 
                        (galleryFilter.value.customizable === 'no' && !d.isCustomizable)
    const matchAi = galleryFilter.value.includeAiAssisted || !d.isAiAssisted
    return matchBreed && matchSport && matchCustom && matchAi
  })
})

// Add this helper function above your onMounted hook
// Grabs the 400x400 webp generated by the Firebase extension
const getThumbnailUrl = (originalUrl) => {
  if (!originalUrl) return 'https://via.placeholder.com/300?text=No+Image';
  
  // 1. Strip off all query parameters (including the mismatched token)
  const baseUrl = originalUrl.split('?')[0];
  
  // 2. Swap the original file extension for the thumbnail suffix
  const thumbnailUrl = baseUrl.replace(/\.[\w\d_-]+$/i, '_400x400.webp');
  
  // 3. Append ONLY ?alt=media so Firebase knows to serve it as an image file
  return `${thumbnailUrl}?alt=media`;
};

onMounted(async () => {

    const auth = getAuth()
  onAuthStateChanged(auth, (user) => {
    currentUser.value = user
  })

  try {
    const q = query(collection(db, 'designs'), where('isActive', '==', true))
    const querySnapshot = await getDocs(q)
    
    designs.value = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error("Error fetching public designs:", error)
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <div class="gallery-container">
    <h2>Design Gallery</h2>
    
    <div v-if="loading" class="loading">Loading designs...</div>
    
    <div v-else-if="designs.length === 0" class="empty-state">No designs available yet.</div>
    
    <template v-else>
      <div class="gallery-filters">
        <div class="gallery-filter-item">
          <label class="gallery-filter-label">Filter by Breed</label>
          <select v-model="galleryFilter.breed" class="gallery-filter-select">
            <option value="">All Breeds</option>
            <option v-for="breed in uniqueBreeds" :key="breed" :value="breed">{{ breed }}</option>
          </select>
        </div>

        <div class="gallery-filter-item">
          <label class="gallery-filter-label">Filter by Sport</label>
          <select v-model="galleryFilter.sport" class="gallery-filter-select">
            <option value="">All Sports</option>
            <option v-for="sport in uniqueSports" :key="sport" :value="sport">{{ sport }}</option>
          </select>
        </div>

        <div class="gallery-filter-item">
          <label class="gallery-filter-label">Customizable</label>
          <select v-model="galleryFilter.customizable" class="gallery-filter-select">
            <option value="">Show All</option>
            <option value="yes">Yes (Add names/colors)</option>
            <option value="no">No</option>
          </select>
        </div>

        <div class="gallery-filter-item gallery-filter-item-checkbox">
          <label class="gallery-checkbox-label">
            <input v-model="galleryFilter.includeAiAssisted" type="checkbox" />
            Include AI-assisted designs
          </label>
        </div>
      </div>
      
      <div v-if="filteredGalleryDesigns.length === 0" class="empty-state filtered-empty-state">
        No designs match your selected filters.
      </div>

      <div v-else class="grid">
        <div v-for="design in filteredGalleryDesigns" :key="design.id" class="card">
          
          <router-link :to="`/design/${design.id}`">
            <img 
              :src="getThumbnailUrl(design.assets?.darkInk || design.assets?.lightInk)" 
              @error="(e) => e.target.src = (design.assets?.darkInk || design.assets?.lightInk)" 
              :alt="design.title" 
              class="card-img" 
            />
          </router-link>
          
          <div class="card-content">
            <router-link :to="`/design/${design.id}`" class="card-title-link">
              <h3>{{ design.title }}</h3>
            </router-link>
            
            <p>{{ design.description }}</p>
            
            <div class="unified-tags-display">
              <span v-for="breed in design.breeds" :key="'b-'+breed" class="tag tag-breed">{{ breed }}</span>
              <span v-for="sport in design.sports" :key="'s-'+sport" class="tag tag-sport">{{ sport }}</span>
              <span v-for="keyword in design.keywords" :key="'k-'+keyword" class="tag tag-keyword">{{ keyword }}</span>
            </div>
            <span v-if="design.isCustomizable" class="tag customizable-tag">Customizable</span>

            <div v-if="currentUser && currentUser.uid === design.ownerId" class="owner-actions">
              <router-link :to="{ path: '/admin', query: { edit: design.id } }" class="btn-primary edit-design-link">
                Edit Design
              </router-link>
            </div>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
.gallery-container { max-width: 1200px; margin: 0 auto; }
.loading, .empty-state { text-align: center; padding: 2rem; color: #666; }

.gallery-filters {
  display: flex;
  gap: 15px;
  margin: 20px 0;
  background: white;
  padding: 15px;
  border-radius: 8px;
  border: 3px solid #1A1A1A;
  box-shadow: 4px 4px 0px rgba(0,0,0,0.1);
  flex-wrap: wrap;
}
.gallery-filter-item {
  flex: 1;
  min-width: 200px;
}
.gallery-filter-label {
  display: block;
  font-size: 0.8rem;
  font-weight: bold;
  margin-bottom: 5px;
  color: #1A1A1A;
}
.gallery-filter-select {
  width: 100%;
  padding: 10px;
  border: 2px solid #ccc;
  border-radius: 6px;
}
.gallery-filter-item-checkbox {
  display: flex;
  align-items: end;
}
.gallery-checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  margin: 0;
  font-size: 0.9rem;
  color: #1A1A1A;
}
.filtered-empty-state {
  margin-top: 40px;
}

.grid { 
  display: grid; 
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); 
  gap: 20px; 
  margin-top: 20px; 
}

.card { 
  border: 1px solid #eaeaea; 
  border-radius: 8px; 
  overflow: hidden; 
  background: white; 
  box-shadow: 0 4px 6px rgba(0,0,0,0.05);
  transition: transform 0.2s ease;
}

.card:hover { transform: translateY(-5px); }

.card-img { 
  width: 100%; 
  height: 250px; 
  object-fit: contain; /* Keeps the whole PNG visible */
  background-color: #f0f0f0; 
  padding: 10px;
  box-sizing: border-box;
}

.card-content { padding: 15px; }
.card-content h3 { margin: 0 0 10px 0; font-size: 1.2rem; color: var(--primary); }
.card-content p { color: #555; font-size: 0.9rem; margin-bottom: 15px; line-height: 1.4; }
.card-title-link {
  text-decoration: none;
}

.tags { display: flex; flex-wrap: wrap; gap: 8px; }
.tag { 
  background: #e9ecef; 
  padding: 4px 8px; 
  border-radius: 12px; 
  font-size: 0.75rem; 
  color: #495057; 
}
.customizable-tag {
  background: var(--accent);
  display: inline-block;
  margin-bottom: 15px;
}
.owner-actions {
  border-top: 1px solid #eee;
  padding-top: 15px;
  margin-top: auto;
}
.edit-design-link {
  font-size: 0.8rem;
  padding: 6px 12px;
  text-decoration: none;
  display: inline-block;
}
</style>