<template>
  <div class="gallery-container">
    <h2>Design Gallery</h2>
    
    <div v-if="loading" class="loading">Loading designs...</div>
    <div v-else-if="designs.length === 0" class="empty-state">No designs available yet.</div>
    
    <div v-else class="grid">
      <div v-for="design in designs" :key="design.id" class="card">
        
        <router-link :to="`/design/${design.id}`">
          <img :src="getThumbnailUrl(design.assets?.darkInk)" @error="(e) => e.target.src = design.assets?.darkInk" :alt="design.title" class="card-img" />
        </router-link>
        
        <div class="card-content">
          <router-link :to="`/design/${design.id}`" style="text-decoration: none;">
            <h3>{{ design.title }}</h3>
          </router-link>
          
          <p>{{ design.description }}</p>
          
          <div class="tags">
            <span v-for="tag in design.keywords" :key="tag" class="tag">{{ tag }}</span>
          </div>

         <div v-if="currentUser && currentUser.uid === design.ownerId" style="margin-top: 15px;">
            <router-link :to="{ path: '/admin', query: { edit: design.id } }" class="btn-primary" style="font-size: 0.8rem; padding: 5px 10px; text-decoration: none; display: inline-block;">
              Edit Design
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { getAuth, onAuthStateChanged } from 'firebase/auth'
import { ref, onMounted } from 'vue'
import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from '../firebase' // Ensure this path matches where you put firebase.js

const designs = ref([])
const loading = ref(true)
const currentUser = ref(null)

// Add this helper function above your onMounted hook
// Grabs the 400x400 webp generated by the Firebase extension
const getThumbnailUrl = (originalUrl) => {
  if (!originalUrl) return 'https://via.placeholder.com/300?text=No+Image';
  
  // 1. Strip off all query parameters (including the mismatched token)
  const baseUrl = originalUrl.split('?')[0];
  
  // 2. Swap the original file extension for the thumbnail suffix
  const thumbnailUrl = baseUrl.replace(/\.[\w\d_-]+$/i, '_400x400.webp');
  
  // 3. Append ONLY ?alt=media so Firebase knows to serve it as an image file
  return `${thumbnailUrl}?alt=media`;
};

onMounted(async () => {

    const auth = getAuth()
  onAuthStateChanged(auth, (user) => {
    currentUser.value = user
  })

  try {
    const q = query(collection(db, 'designs'), where('isActive', '==', true))
    const querySnapshot = await getDocs(q)
    
    designs.value = querySnapshot.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    }))
  } catch (error) {
    console.error("Error fetching public designs:", error)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.gallery-container { max-width: 1200px; margin: 0 auto; }
.loading, .empty-state { text-align: center; padding: 2rem; color: #666; }

.grid { 
  display: grid; 
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); 
  gap: 20px; 
  margin-top: 20px; 
}

.card { 
  border: 1px solid #eaeaea; 
  border-radius: 8px; 
  overflow: hidden; 
  background: white; 
  box-shadow: 0 4px 6px rgba(0,0,0,0.05);
  transition: transform 0.2s ease;
}

.card:hover { transform: translateY(-5px); }

.card-img { 
  width: 100%; 
  height: 250px; 
  object-fit: contain; /* Keeps the whole PNG visible */
  background-color: #f0f0f0; 
  padding: 10px;
  box-sizing: border-box;
}

.card-content { padding: 15px; }
.card-content h3 { margin: 0 0 10px 0; font-size: 1.2rem; color: var(--primary); }
.card-content p { color: #555; font-size: 0.9rem; margin-bottom: 15px; line-height: 1.4; }

.tags { display: flex; flex-wrap: wrap; gap: 8px; }
.tag { 
  background: #e9ecef; 
  padding: 4px 8px; 
  border-radius: 12px; 
  font-size: 0.75rem; 
  color: #495057; 
}
</style>